# Generated by Django 2.2.5 on 2019-09-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('coursenum', models.AutoField(db_column='courseNum', primary_key=True, serialize=False)),
                ('coursecode', models.CharField(blank=True, db_column='courseCode', max_length=10)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('sectionnum', models.AutoField(db_column='sectionNum', primary_key=True, serialize=False)),
                ('semester', models.CharField(blank=True, max_length=1)),
                ('section', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'db_table': 'sections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('daynum', models.IntegerField(db_column='dayNum', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'slots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teachernum', models.AutoField(db_column='teacherNum', primary_key=True, serialize=False)),
                ('teachername', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'teachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeslots',
            fields=[
                ('timeslotnum', models.AutoField(db_column='timeSlotNum', primary_key=True, serialize=False)),
                ('starttime', models.TimeField(blank=True, db_column='startTime')),
                ('endtime', models.TimeField(blank=True, db_column='endTime')),
            ],
            options={
                'db_table': 'timeslots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('venuenum', models.AutoField(db_column='venueNum', primary_key=True, serialize=False)),
                ('venuename', models.CharField(db_column='venueName', max_length=6)),
            ],
            options={
                'db_table': 'venues',
                'managed': False,
            },
        ),
    ]
